# Generated by Django 5.2.7 on 2025-11-05 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_delete_batchprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_risk', models.FloatField(default=0.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='inventory.batch')),
            ],
        ),
    ]
