# Generated by Django 5.2.7 on 2025-11-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_batchprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('high_risk_count', models.IntegerField(default=0)),
                ('medium_risk_count', models.IntegerField(default=0)),
                ('low_risk_count', models.IntegerField(default=0)),
                ('total_predictions', models.IntegerField(default=0)),
            ],
        ),
    ]
