# Generated by Django 5.2.7 on 2025-11-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_riskhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskhistory',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
